# Generated by Django 5.2.1 on 2025-08-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
    ]
